variables:
  EXAMPLE_VAR: DEFAULT_VAL

stages:
  - triggers

trigger_k8s:
  stage: triggers
  trigger:
    include: kubernetes/.gitlab-ci.yml
  rules:
    - changes:
      - kubernetes/*
