stages:
  - build
  - test
  - deploy

apps:build:
  stage: build
  script:
    - echo "This job builds something."

apps:test:
  stage: test
  needs: ["apps:build"]
  script:
    - echo "This job tests something."

apps:deploy:
  stage: deploy
  needs: ["apps:test"]
  script:
    - echo "This job deploys something."
